wholeslidedata:
  default:
    seed: 123
    yaml_source: data_split_stratified.yml

    label_map:
      none: 0
      epithelium benign: 1
      epithelium hyperplasia: 2
      epithelium atypia: 3
      epithelium malignant: 4
      rest: 5
      stroma: 6
      stroma malignant: 6
      necrosis: 5
      myometrium: 5

    renamed_labels:
      none: 0
      epithelium benign: 1
      epithelium hyperplasia: 2
      epithelium atypia: 3
      epithelium malignant: 4
      rest: 5
      stroma: 6

    annotation_parser:
      sample_label_names: [ 'none' ]

    label_sampler:
      attribute: OrderedLabelSampler

    annotation_sampler:
      attribute: OrderedAnnotationSampler

    point_sampler:
      attribute: RandomPointSampler
      buffer: -256

    batch_shape:
      batch_size: 2
      shape: [[512, 512, 3], [512, 512, 3]]
      spacing: [ 0.5, 4.0 ]
      y_shape: [2, 512, 512, 6 ]

    sample_callbacks:
      - module: wholeslidedata.samplers.callbacks
        attribute: OneHotEncoding
        labels: ${wholeslidedata:labels}
    
    dataset:
      copy_path: /home/user/data
